-- One permanent EcoSphere installation with replaceable ESP32 controllers.
-- Existing telemetry and control targets remain attached to device_control id=1.

create table private.ecosystems (
  id smallint primary key default 1,
  name text not null default 'EcoSphere principal',
  active_controller_id bigint,
  legacy_writes_allowed boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint ecosystems_singleton check (id = 1),
  constraint ecosystems_name_length check (char_length(name) between 3 and 80)
);

create table private.device_controllers (
  id bigint generated by default as identity primary key,
  ecosystem_id smallint not null default 1
    references private.ecosystems(id) on delete restrict,
  hardware_uid text not null,
  secret_hash bytea not null,
  pairing_code_hash bytea,
  pairing_expires_at timestamptz,
  status text not null default 'pending',
  firmware_version text,
  first_seen_at timestamptz not null default now(),
  last_seen_at timestamptz,
  activated_at timestamptz,
  activated_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint device_controllers_hardware_uid_format
    check (hardware_uid ~ '^[0-9A-F]{12}$'),
  constraint device_controllers_status
    check (status in ('pending', 'active', 'standby', 'revoked')),
  constraint device_controllers_firmware_length
    check (firmware_version is null or char_length(firmware_version) between 1 and 40),
  constraint device_controllers_pairing_state check (
    (pairing_code_hash is null and pairing_expires_at is null)
    or (pairing_code_hash is not null and pairing_expires_at is not null)
  )
);

create unique index device_controllers_hardware_uid_unique
  on private.device_controllers (hardware_uid);
create index device_controllers_ecosystem_id_idx
  on private.device_controllers (ecosystem_id);
create index device_controllers_pairing_code_hash_idx
  on private.device_controllers (pairing_code_hash)
  where pairing_code_hash is not null;
create unique index device_controllers_one_active_per_ecosystem
  on private.device_controllers (ecosystem_id)
  where status = 'active';

alter table private.ecosystems
  add constraint ecosystems_active_controller_fk
  foreign key (active_controller_id)
  references private.device_controllers(id)
  on delete set null;

create index ecosystems_active_controller_id_idx
  on private.ecosystems (active_controller_id)
  where active_controller_id is not null;

create table private.controller_events (
  id bigint generated by default as identity primary key,
  ecosystem_id smallint not null
    references private.ecosystems(id) on delete restrict,
  controller_id bigint
    references private.device_controllers(id) on delete set null,
  event_type text not null,
  actor_user_id uuid references auth.users(id) on delete set null,
  details jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  constraint controller_events_type check (
    event_type in (
      'pairing_started',
      'controller_activated',
      'controller_replaced',
      'secure_mode_enabled'
    )
  ),
  constraint controller_events_details_object
    check (jsonb_typeof(details) = 'object')
);

create index controller_events_ecosystem_created_idx
  on private.controller_events (ecosystem_id, created_at desc);
create index controller_events_controller_id_idx
  on private.controller_events (controller_id)
  where controller_id is not null;

alter table private.ecosystems enable row level security;
alter table private.ecosystems force row level security;
alter table private.device_controllers enable row level security;
alter table private.device_controllers force row level security;
alter table private.controller_events enable row level security;
alter table private.controller_events force row level security;

revoke all on table private.ecosystems from public, anon, authenticated;
revoke all on table private.device_controllers from public, anon, authenticated;
revoke all on table private.controller_events from public, anon, authenticated;
revoke all on sequence private.device_controllers_id_seq from public, anon, authenticated;
revoke all on sequence private.controller_events_id_seq from public, anon, authenticated;

insert into private.ecosystems (id)
values (1);

alter table public.sensor_records
  add column controller_id bigint
    references private.device_controllers(id) on delete set null;

create index sensor_records_controller_created_idx
  on public.sensor_records (controller_id, created_at desc)
  where controller_id is not null;

alter table public.device_control
  add column active_controller_id bigint
    references private.device_controllers(id) on delete set null;

create index device_control_active_controller_id_idx
  on public.device_control (active_controller_id)
  where active_controller_id is not null;

-- Do not mark a newly selected replacement online merely because its id changed.
create or replace function public.set_esp32_last_seen()
returns trigger
language plpgsql
set search_path = 'pg_catalog'
as $$
begin
  new.updated_at = now();

  if new.active_controller_id is not distinct from old.active_controller_id
     and new.heartbeat_seq is distinct from old.heartbeat_seq then
    new.last_seen_at = now();
    new.esp32_online = true;
  end if;

  return new;
end;
$$;

create function public.legacy_controller_writes_allowed()
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select coalesce((
    select e.legacy_writes_allowed
    from private.ecosystems e
    where e.id = 1
  ), false);
$$;

revoke all on function public.legacy_controller_writes_allowed()
  from public, anon, authenticated;
grant execute on function public.legacy_controller_writes_allowed()
  to anon;

drop policy if exists "allow_select_device_control" on public.device_control;
create policy "allow_legacy_select_device_control"
  on public.device_control
  for select
  to anon
  using (
    id = 1
    and (select public.legacy_controller_writes_allowed())
  );

drop policy if exists "allow_update_device_control" on public.device_control;
create policy "allow_legacy_update_device_control"
  on public.device_control
  for update
  to anon
  using (
    id = 1
    and (select public.legacy_controller_writes_allowed())
  )
  with check (
    id = 1
    and (select public.legacy_controller_writes_allowed())
  );

drop policy if exists "allow_select_sensor_records" on public.sensor_records;
create policy "allow_legacy_select_sensor_records"
  on public.sensor_records
  for select
  to anon
  using ((select public.legacy_controller_writes_allowed()));

drop policy if exists "allow_insert_sensor_records" on public.sensor_records;
create policy "allow_legacy_insert_sensor_records"
  on public.sensor_records
  for insert
  to anon
  with check (
    controller_id is null
    and (select public.legacy_controller_writes_allowed())
  );

create function private.require_admin_aal2()
returns uuid
language plpgsql
stable
security definer
set search_path = ''
as $$
declare
  v_user_id uuid := (select auth.uid());
begin
  if v_user_id is null then
    raise exception 'authentication required' using errcode = '42501';
  end if;

  if coalesce((select auth.jwt()->>'aal'), '') <> 'aal2' then
    raise exception 'two-factor authentication required' using errcode = '42501';
  end if;

  if not exists (
    select 1
    from private.user_profiles p
    where p.user_id = v_user_id
      and p.status = 'approved'
      and p.role = 'admin'
  ) then
    raise exception 'administrator access required' using errcode = '42501';
  end if;

  return v_user_id;
end;
$$;

revoke all on function private.require_admin_aal2()
  from public, anon, authenticated;

create function public.controller_begin_pairing(
  p_hardware_uid text,
  p_device_secret text,
  p_firmware_version text default null
)
returns table (
  pairing_code text,
  expires_at timestamptz,
  controller_status text
)
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_hardware_uid text := upper(regexp_replace(coalesce(p_hardware_uid, ''), '[^0-9A-Fa-f]', '', 'g'));
  v_secret text := lower(trim(coalesce(p_device_secret, '')));
  v_secret_hash bytea;
  v_code_plain text := upper(extensions.encode(extensions.gen_random_bytes(6), 'hex'));
  v_code_hash bytea;
  v_controller private.device_controllers%rowtype;
  v_expires_at timestamptz := now() + interval '15 minutes';
begin
  if v_hardware_uid !~ '^[0-9A-F]{12}$' then
    raise exception 'invalid controller hardware uid' using errcode = '22023';
  end if;

  if v_secret !~ '^[0-9a-f]{64}$' then
    raise exception 'invalid controller secret' using errcode = '22023';
  end if;

  if p_firmware_version is not null
     and char_length(trim(p_firmware_version)) not between 1 and 40 then
    raise exception 'invalid firmware version' using errcode = '22023';
  end if;

  v_secret_hash := extensions.digest(v_secret, 'sha256');
  v_code_hash := extensions.digest(v_code_plain, 'sha256');

  select *
    into v_controller
  from private.device_controllers c
  where c.hardware_uid = v_hardware_uid
  for update;

  if found then
    if v_controller.secret_hash <> v_secret_hash then
      raise exception 'controller identity mismatch' using errcode = '42501';
    end if;

    if v_controller.status = 'active' then
      return query
        select null::text, null::timestamptz, 'active'::text;
      return;
    end if;

    if v_controller.status = 'revoked' then
      raise exception 'controller has been revoked' using errcode = '42501';
    end if;

    update private.device_controllers
      set pairing_code_hash = v_code_hash,
          pairing_expires_at = v_expires_at,
          status = 'pending',
          firmware_version = coalesce(nullif(trim(p_firmware_version), ''), firmware_version),
          updated_at = now()
    where id = v_controller.id
    returning * into v_controller;
  else
    insert into private.device_controllers (
      ecosystem_id,
      hardware_uid,
      secret_hash,
      pairing_code_hash,
      pairing_expires_at,
      firmware_version
    )
    values (
      1,
      v_hardware_uid,
      v_secret_hash,
      v_code_hash,
      v_expires_at,
      nullif(trim(p_firmware_version), '')
    )
    returning * into v_controller;
  end if;

  insert into private.controller_events (
    ecosystem_id,
    controller_id,
    event_type,
    details
  )
  values (
    1,
    v_controller.id,
    'pairing_started',
    jsonb_build_object('firmware_version', v_controller.firmware_version)
  );

  return query
    select
      substring(v_code_plain from 1 for 4) || '-' ||
        substring(v_code_plain from 5 for 4) || '-' ||
        substring(v_code_plain from 9 for 4),
      v_expires_at,
      'pending'::text;
end;
$$;

revoke all on function public.controller_begin_pairing(text, text, text)
  from public, anon, authenticated;
grant execute on function public.controller_begin_pairing(text, text, text)
  to anon;

create function public.replace_active_controller(p_pairing_code text)
returns table (
  controller_id bigint,
  hardware_uid_masked text,
  controller_status text,
  firmware_version text,
  secure_mode boolean
)
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_user_id uuid := private.require_admin_aal2();
  v_code text := upper(regexp_replace(coalesce(p_pairing_code, ''), '[^0-9A-Fa-f]', '', 'g'));
  v_code_hash bytea;
  v_controller private.device_controllers%rowtype;
  v_previous_controller_id bigint;
  v_legacy_writes_allowed boolean;
begin
  if v_code !~ '^[0-9A-F]{12}$' then
    raise exception 'invalid pairing code' using errcode = '22023';
  end if;

  v_code_hash := extensions.digest(v_code, 'sha256');

  select e.active_controller_id, e.legacy_writes_allowed
    into v_previous_controller_id, v_legacy_writes_allowed
  from private.ecosystems e
  where e.id = 1
  for update;

  select *
    into v_controller
  from private.device_controllers c
  where c.ecosystem_id = 1
    and c.status = 'pending'
    and c.pairing_code_hash = v_code_hash
    and c.pairing_expires_at > now()
  for update;

  if not found then
    raise exception 'pairing code is invalid or expired' using errcode = '22023';
  end if;

  update private.device_controllers
    set status = 'standby',
        pairing_code_hash = null,
        pairing_expires_at = null,
        updated_at = now()
  where ecosystem_id = 1
    and status = 'active'
    and id <> v_controller.id;

  update private.device_controllers
    set status = 'active',
        pairing_code_hash = null,
        pairing_expires_at = null,
        activated_at = now(),
        activated_by = v_user_id,
        updated_at = now()
  where id = v_controller.id
  returning * into v_controller;

  update private.ecosystems
    set active_controller_id = v_controller.id,
        updated_at = now()
  where id = 1;

  update public.device_control
    set active_controller_id = v_controller.id,
        esp32_online = false,
        last_seen_at = null,
        heartbeat_seq = 0
  where id = 1;

  insert into private.controller_events (
    ecosystem_id,
    controller_id,
    event_type,
    actor_user_id,
    details
  )
  values (
    1,
    v_controller.id,
    case
      when v_previous_controller_id is null then 'controller_activated'
      else 'controller_replaced'
    end,
    v_user_id,
    jsonb_build_object('previous_controller_id', v_previous_controller_id)
  );

  return query
    select
      v_controller.id,
      '********' || right(v_controller.hardware_uid, 4),
      v_controller.status,
      v_controller.firmware_version,
      not v_legacy_writes_allowed;
end;
$$;

revoke all on function public.replace_active_controller(text)
  from public, anon, authenticated;
grant execute on function public.replace_active_controller(text)
  to authenticated;

create function public.controller_admin_status()
returns table (
  controller_id bigint,
  hardware_uid_masked text,
  controller_status text,
  firmware_version text,
  last_seen_at timestamptz,
  secure_mode boolean
)
language plpgsql
stable
security definer
set search_path = ''
as $$
begin
  perform private.require_admin_aal2();

  return query
    select
      c.id,
      case when c.id is null then null else '********' || right(c.hardware_uid, 4) end,
      coalesce(c.status, 'not_paired'),
      c.firmware_version,
      c.last_seen_at,
      not e.legacy_writes_allowed
    from private.ecosystems e
    left join private.device_controllers c
      on c.id = e.active_controller_id
    where e.id = 1;
end;
$$;

revoke all on function public.controller_admin_status()
  from public, anon, authenticated;
grant execute on function public.controller_admin_status()
  to authenticated;

create function public.controller_sync(
  p_hardware_uid text,
  p_device_secret text,
  p_heartbeat_seq bigint,
  p_firmware_version text default null,
  p_has_telemetry boolean default false,
  p_temperature double precision default null,
  p_air_humidity double precision default null,
  p_soil_humidity double precision default null,
  p_light_lux double precision default null,
  p_water_level text default null,
  p_fan_on boolean default null,
  p_pump_on boolean default null,
  p_led_on boolean default null,
  p_reported_auto_mode boolean default null,
  p_reported_fan_power integer default null,
  p_reported_led_power integer default null
)
returns table (
  fan_target boolean,
  led_target boolean,
  auto_mode boolean,
  pump_request bigint,
  pump_duration_ms integer,
  fan_power integer,
  led_power integer,
  secure_mode boolean
)
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_hardware_uid text := upper(regexp_replace(coalesce(p_hardware_uid, ''), '[^0-9A-Fa-f]', '', 'g'));
  v_secret text := lower(trim(coalesce(p_device_secret, '')));
  v_secret_hash bytea;
  v_controller private.device_controllers%rowtype;
  v_secure_mode_just_enabled boolean := false;
begin
  if v_hardware_uid !~ '^[0-9A-F]{12}$'
     or v_secret !~ '^[0-9a-f]{64}$'
     or p_heartbeat_seq is null
     or p_heartbeat_seq < 0 then
    raise exception 'invalid controller credentials or heartbeat' using errcode = '22023';
  end if;

  if p_firmware_version is not null
     and char_length(trim(p_firmware_version)) not between 1 and 40 then
    raise exception 'invalid firmware version' using errcode = '22023';
  end if;

  v_secret_hash := extensions.digest(v_secret, 'sha256');

  select c.*
    into v_controller
  from private.device_controllers c
  join private.ecosystems e
    on e.id = c.ecosystem_id
   and e.active_controller_id = c.id
  where c.hardware_uid = v_hardware_uid
    and c.secret_hash = v_secret_hash
    and c.status = 'active'
  for update of c;

  if not found then
    raise exception 'controller is not active' using errcode = '42501';
  end if;

  update private.ecosystems
    set legacy_writes_allowed = false,
        updated_at = now()
  where id = 1
    and legacy_writes_allowed
  returning true into v_secure_mode_just_enabled;

  update private.device_controllers
    set last_seen_at = now(),
        firmware_version = coalesce(nullif(trim(p_firmware_version), ''), firmware_version),
        updated_at = now()
  where id = v_controller.id;

  update public.device_control
    set heartbeat_seq = p_heartbeat_seq,
        esp32_online = true,
        last_seen_at = now()
  where id = 1
    and active_controller_id = v_controller.id;

  if p_has_telemetry then
    insert into public.sensor_records (
      controller_id,
      temperature,
      air_humidity,
      soil_humidity,
      light_lux,
      water_level,
      fan_on,
      pump_on,
      led_on,
      auto_mode,
      fan_power,
      led_power
    )
    values (
      v_controller.id,
      p_temperature,
      p_air_humidity,
      p_soil_humidity,
      p_light_lux,
      case when p_water_level is null then null else lower(p_water_level) end,
      p_fan_on,
      p_pump_on,
      p_led_on,
      p_reported_auto_mode,
      p_reported_fan_power,
      p_reported_led_power
    );
  end if;

  if coalesce(v_secure_mode_just_enabled, false) then
    insert into private.controller_events (
      ecosystem_id,
      controller_id,
      event_type
    )
    values (1, v_controller.id, 'secure_mode_enabled');
  end if;

  return query
    select
      d.fan_target,
      d.led_target,
      d.auto_mode,
      d.pump_request,
      d.pump_duration_ms,
      d.fan_power,
      d.led_power,
      true
    from public.device_control d
    where d.id = 1;
end;
$$;

revoke all on function public.controller_sync(
  text,
  text,
  bigint,
  text,
  boolean,
  double precision,
  double precision,
  double precision,
  double precision,
  text,
  boolean,
  boolean,
  boolean,
  boolean,
  integer,
  integer
) from public, anon, authenticated;
grant execute on function public.controller_sync(
  text,
  text,
  bigint,
  text,
  boolean,
  double precision,
  double precision,
  double precision,
  double precision,
  text,
  boolean,
  boolean,
  boolean,
  boolean,
  integer,
  integer
) to anon;


