-- Reconstructs the original dashboard-created schema so a fresh project can
-- replay every checked-in migration. Production already records this version.

create or replace function public.rls_auto_enable()
returns event_trigger
language plpgsql
security definer
set search_path = pg_catalog
as $$
declare
  command record;
begin
  for command in
    select *
    from pg_event_trigger_ddl_commands()
    where command_tag in ('CREATE TABLE', 'CREATE TABLE AS', 'SELECT INTO')
      and object_type in ('table', 'partitioned table')
  loop
    if command.schema_name = 'public' then
      begin
        execute format(
          'alter table if exists %s enable row level security',
          command.object_identity
        );
      exception when others then
        raise log 'rls_auto_enable: failed to enable RLS on %', command.object_identity;
      end;
    end if;
  end loop;
end;
$$;

create event trigger ensure_rls
on ddl_command_end
when tag in ('CREATE TABLE', 'CREATE TABLE AS', 'SELECT INTO')
execute function public.rls_auto_enable();

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create table public.sensor_records (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  temperature double precision,
  air_humidity double precision,
  soil_humidity double precision,
  light_lux double precision,
  water_level text,
  fan_on boolean,
  pump_on boolean,
  led_on boolean,
  auto_mode boolean
);

create table public.device_control (
  id integer primary key default 1,
  fan_target boolean not null default false,
  led_target boolean not null default false,
  auto_mode boolean not null default false,
  pump_request bigint not null default 0,
  pump_duration_ms integer not null default 3000,
  esp32_online boolean not null default false,
  last_seen_at timestamptz,
  updated_at timestamptz not null default now(),
  constraint device_control_id_check check (id = 1)
);

create trigger trg_device_control_updated_at
before update on public.device_control
for each row execute function public.set_updated_at();

insert into public.device_control (id) values (1);

alter table public.sensor_records enable row level security;
alter table public.device_control enable row level security;

create policy "allow_select_sensor_records"
  on public.sensor_records for select to anon, authenticated using (true);
create policy "allow_insert_sensor_records"
  on public.sensor_records for insert to anon, authenticated with check (true);
create policy "allow_select_device_control"
  on public.device_control for select to anon, authenticated using (id = 1);
create policy "allow_update_device_control"
  on public.device_control for update to anon, authenticated
  using (id = 1) with check (id = 1);

grant select, insert on public.sensor_records to anon, authenticated;
grant usage, select on sequence public.sensor_records_id_seq to anon, authenticated;
grant select, update on public.device_control to anon, authenticated;
